import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// inside <header> or wherever
<nav className="space-x-4">
  <a href="/sessions" className="hover:underline">Sessions</a>
  <a href="/goals"    className="hover:underline">Goals</a>
  <a href="/reflections" className="hover:underline">Reflections</a>
</nav>

